### ISSUE TITLE
Mutter standalone startup problems

### ISSUE THREAD

**Issue by sksar** [timbertson/mutter#1]
Mutter is having loads of problems when starting up standlone using the command mutter --replace in a terminal.
Mutter attaches an extra title bar with only the title "tweak tool". 
Maximize and minimization does not work properly.
Themes are not loaded properly.

**Comment by timbertson** [comment]
Are you using my fork of mutter? This is not the official gnome mutter, and has not been updated in 5 years. I should delete it actually, as all my changes are either merged into mainline or abandoned.
